### ISSUE TITLE
Entity generated id should not be overwritten

### ISSUE THREAD

**Issue by pskrzypek84** [LukaszPiskadlo/Pat2017_Lukasz_Piskadlo-Backend#5]
Scenario:
1. Create Actor (POST)
2. Update Actor and change ID in request (PUT)

This bug reveals problem with duplicated ID when we POST subsequent entities.

**Comment by LukaszPiskadlo** [comment]
If you were checking this on branch [Zad_1](https://github.com/LukaszPiskadlo/Pat2017_Lukasz_Piskadlo-Backend/tree/Zad_1) could you please check again? I forgot to update that branch after recent commits.
